version: '3'
services:
    # configurações do servico de frontend
  frontend:
    build: frontend/
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend

    # configurações do servico de backend
  backend:
    build: backend/
    ports:
      - 3001:3001
    restart: on-failure
    environment:
      - DB_HOST=database
    depends_on:
      - database

    # configurações do servico de database
  database:
    image: betrybe/docker-compose-example-database:v1 
    restart: on-failure